# Application Configuration
spring:
  application:
    name: student-management
  
  # Database Configuration (PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5432/order_management
    username: postgres
    password: Password@123
    driver-class-name: org.postgresql.Driver
    
    # Connection Pool Configuration
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  
  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Server Configuration
server:
  port: 8080
  address: 0.0.0.0

# JWT Configuration
jwt:
  secret: mySecretKeyForStudentManagementSystemJWTTokenGeneration2024
  expiration: 86400000 # 24 hours in milliseconds


# Application specific configuration
app:
  upload:
    dir: uploads

# Logging Configuration
logging:
  level:
    com.example.studentmanagement: DEBUG
    org.springframework.web: DEBUG
